#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vintage.AppServices.DataAccessClasses
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="NZULM")]
	public partial class NzUlmDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public NzUlmDataContext() : 
				base(global::Vintage.AppServices.Properties.Settings.Default.NZULMConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public NzUlmDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NzUlmDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NzUlmDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public NzUlmDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetNZULM_PrescribingTerm", IsComposable=true)]
		public IQueryable<GetNZULM_PrescribingTermResult> GetNZULM_PrescribingTerm([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Term", DbType="VarChar(MAX)")] string term, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TermType", DbType="VarChar(10)")] string termType)
		{
			return this.CreateMethodCallQuery<GetNZULM_PrescribingTermResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), term, termType);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetMedicinalProduct_Substance_ByProductCode", IsComposable=true)]
		public IQueryable<GetMedicinalProduct_Substance_ByProductCodeResult> GetMedicinalProduct_Substance_ByProductCode([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Code", DbType="VarChar(19)")] string code)
		{
			return this.CreateMethodCallQuery<GetMedicinalProduct_Substance_ByProductCodeResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), code);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetMedicinalProduct_ByTerm", IsComposable=true)]
		public IQueryable<GetMedicinalProduct_ByTermResult> GetMedicinalProduct_ByTerm([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Term", DbType="VarChar(MAX)")] string term)
		{
			return this.CreateMethodCallQuery<GetMedicinalProduct_ByTermResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), term);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetTradeProduct_ByTerm", IsComposable=true)]
		public IQueryable<GetTradeProduct_ByTermResult> GetTradeProduct_ByTerm([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Term", DbType="VarChar(MAX)")] string term)
		{
			return this.CreateMethodCallQuery<GetTradeProduct_ByTermResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), term);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetContaineredTradeProductPack_ByTerm", IsComposable=true)]
		public IQueryable<GetContaineredTradeProductPack_ByTermResult> GetContaineredTradeProductPack_ByTerm([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Term", DbType="VarChar(MAX)")] string term)
		{
			return this.CreateMethodCallQuery<GetContaineredTradeProductPack_ByTermResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), term);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetMedicinalProductPack_ByTerm", IsComposable=true)]
		public IQueryable<GetMedicinalProductPack_ByTermResult> GetMedicinalProductPack_ByTerm([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Term", DbType="VarChar(MAX)")] string term)
		{
			return this.CreateMethodCallQuery<GetMedicinalProductPack_ByTermResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), term);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetMedicinalProductUnitOfUse_ByTerm", IsComposable=true)]
		public IQueryable<GetMedicinalProductUnitOfUse_ByTermResult> GetMedicinalProductUnitOfUse_ByTerm([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Term", DbType="VarChar(MAX)")] string term)
		{
			return this.CreateMethodCallQuery<GetMedicinalProductUnitOfUse_ByTermResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), term);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetTradeProductPack_ByTerm", IsComposable=true)]
		public IQueryable<GetTradeProductPack_ByTermResult> GetTradeProductPack_ByTerm([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Term", DbType="VarChar(MAX)")] string term)
		{
			return this.CreateMethodCallQuery<GetTradeProductPack_ByTermResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), term);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetTradeProductUnitOfUse_ByTerm", IsComposable=true)]
		public IQueryable<GetTradeProductUnitOfUse_ByTermResult> GetTradeProductUnitOfUse_ByTerm([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Term", DbType="VarChar(MAX)")] string term)
		{
			return this.CreateMethodCallQuery<GetTradeProductUnitOfUse_ByTermResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), term);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetCttp_Related_IDs_ByCode", IsComposable=true)]
		public IQueryable<GetCttp_Related_IDs_ByCodeResult> GetCttp_Related_IDs_ByCode([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Code", DbType="VarChar(19)")] string code)
		{
			return this.CreateMethodCallQuery<GetCttp_Related_IDs_ByCodeResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), code);
		}
	}
	
	public partial class GetNZULM_PrescribingTermResult
	{
		
		private string _concept_id;
		
		private string _prescribing_term;
		
		private string _term_type;
		
		public GetNZULM_PrescribingTermResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_concept_id", DbType="VarChar(19) NOT NULL", CanBeNull=false)]
		public string concept_id
		{
			get
			{
				return this._concept_id;
			}
			set
			{
				if ((this._concept_id != value))
				{
					this._concept_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_prescribing_term", DbType="NVarChar(255)")]
		public string prescribing_term
		{
			get
			{
				return this._prescribing_term;
			}
			set
			{
				if ((this._prescribing_term != value))
				{
					this._prescribing_term = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_term_type", DbType="VarChar(10)")]
		public string term_type
		{
			get
			{
				return this._term_type;
			}
			set
			{
				if ((this._term_type != value))
				{
					this._term_type = value;
				}
			}
		}
	}
	
	public partial class GetMedicinalProduct_Substance_ByProductCodeResult
	{
		
		private string _Product_Code;
		
		private string _PreferredTerm;
		
		private string _FullySpecifiedName;
		
		private bool _BaseSubstance_;
		
		private string _Ingredient;
		
		private string _LessModifiedIngredient;
		
		public GetMedicinalProduct_Substance_ByProductCodeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Product Code]", Storage="_Product_Code", DbType="VarChar(19) NOT NULL", CanBeNull=false)]
		public string Product_Code
		{
			get
			{
				return this._Product_Code;
			}
			set
			{
				if ((this._Product_Code != value))
				{
					this._Product_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PreferredTerm", DbType="NVarChar(1000)")]
		public string PreferredTerm
		{
			get
			{
				return this._PreferredTerm;
			}
			set
			{
				if ((this._PreferredTerm != value))
				{
					this._PreferredTerm = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullySpecifiedName", DbType="NVarChar(1000)")]
		public string FullySpecifiedName
		{
			get
			{
				return this._FullySpecifiedName;
			}
			set
			{
				if ((this._FullySpecifiedName != value))
				{
					this._FullySpecifiedName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[BaseSubstance?]", Storage="_BaseSubstance_", DbType="Bit NOT NULL")]
		public bool BaseSubstance_
		{
			get
			{
				return this._BaseSubstance_;
			}
			set
			{
				if ((this._BaseSubstance_ != value))
				{
					this._BaseSubstance_ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ingredient", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Ingredient
		{
			get
			{
				return this._Ingredient;
			}
			set
			{
				if ((this._Ingredient != value))
				{
					this._Ingredient = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LessModifiedIngredient", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string LessModifiedIngredient
		{
			get
			{
				return this._LessModifiedIngredient;
			}
			set
			{
				if ((this._LessModifiedIngredient != value))
				{
					this._LessModifiedIngredient = value;
				}
			}
		}
	}
	
	public partial class GetMedicinalProduct_ByTermResult
	{
		
		private string _Product_Code;
		
		private string _Preferred_Term;
		
		private bool _Base_Substance_;
		
		public GetMedicinalProduct_ByTermResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Product Code]", Storage="_Product_Code", DbType="VarChar(19) NOT NULL", CanBeNull=false)]
		public string Product_Code
		{
			get
			{
				return this._Product_Code;
			}
			set
			{
				if ((this._Product_Code != value))
				{
					this._Product_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Preferred Term]", Storage="_Preferred_Term", DbType="NVarChar(1000)")]
		public string Preferred_Term
		{
			get
			{
				return this._Preferred_Term;
			}
			set
			{
				if ((this._Preferred_Term != value))
				{
					this._Preferred_Term = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Base Substance?]", Storage="_Base_Substance_", DbType="Bit NOT NULL")]
		public bool Base_Substance_
		{
			get
			{
				return this._Base_Substance_;
			}
			set
			{
				if ((this._Base_Substance_ != value))
				{
					this._Base_Substance_ = value;
				}
			}
		}
	}
	
	public partial class GetTradeProduct_ByTermResult
	{
		
		private string _Product_Code;
		
		private string _Preferred_Term;
		
		public GetTradeProduct_ByTermResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Product Code]", Storage="_Product_Code", DbType="VarChar(19) NOT NULL", CanBeNull=false)]
		public string Product_Code
		{
			get
			{
				return this._Product_Code;
			}
			set
			{
				if ((this._Product_Code != value))
				{
					this._Product_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Preferred Term]", Storage="_Preferred_Term", DbType="NVarChar(1000)")]
		public string Preferred_Term
		{
			get
			{
				return this._Preferred_Term;
			}
			set
			{
				if ((this._Preferred_Term != value))
				{
					this._Preferred_Term = value;
				}
			}
		}
	}
	
	public partial class GetContaineredTradeProductPack_ByTermResult
	{
		
		private string _Containered_Pack_Code;
		
		private string _Preferred_Term;
		
		public GetContaineredTradeProductPack_ByTermResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Containered Pack Code]", Storage="_Containered_Pack_Code", DbType="VarChar(19) NOT NULL", CanBeNull=false)]
		public string Containered_Pack_Code
		{
			get
			{
				return this._Containered_Pack_Code;
			}
			set
			{
				if ((this._Containered_Pack_Code != value))
				{
					this._Containered_Pack_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Preferred Term]", Storage="_Preferred_Term", DbType="NVarChar(1000)")]
		public string Preferred_Term
		{
			get
			{
				return this._Preferred_Term;
			}
			set
			{
				if ((this._Preferred_Term != value))
				{
					this._Preferred_Term = value;
				}
			}
		}
	}
	
	public partial class GetMedicinalProductPack_ByTermResult
	{
		
		private string _Pack_Code;
		
		private string _Preferred_Term;
		
		public GetMedicinalProductPack_ByTermResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Pack Code]", Storage="_Pack_Code", DbType="VarChar(19) NOT NULL", CanBeNull=false)]
		public string Pack_Code
		{
			get
			{
				return this._Pack_Code;
			}
			set
			{
				if ((this._Pack_Code != value))
				{
					this._Pack_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Preferred Term]", Storage="_Preferred_Term", DbType="NVarChar(1000)")]
		public string Preferred_Term
		{
			get
			{
				return this._Preferred_Term;
			}
			set
			{
				if ((this._Preferred_Term != value))
				{
					this._Preferred_Term = value;
				}
			}
		}
	}
	
	public partial class GetMedicinalProductUnitOfUse_ByTermResult
	{
		
		private string _Unit_of_Use_Code;
		
		private string _Preferred_Term;
		
		public GetMedicinalProductUnitOfUse_ByTermResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Unit of Use Code]", Storage="_Unit_of_Use_Code", DbType="VarChar(19) NOT NULL", CanBeNull=false)]
		public string Unit_of_Use_Code
		{
			get
			{
				return this._Unit_of_Use_Code;
			}
			set
			{
				if ((this._Unit_of_Use_Code != value))
				{
					this._Unit_of_Use_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Preferred Term]", Storage="_Preferred_Term", DbType="NVarChar(1000)")]
		public string Preferred_Term
		{
			get
			{
				return this._Preferred_Term;
			}
			set
			{
				if ((this._Preferred_Term != value))
				{
					this._Preferred_Term = value;
				}
			}
		}
	}
	
	public partial class GetTradeProductPack_ByTermResult
	{
		
		private string _Product_Pack_Code;
		
		private string _Preferred_Term;
		
		public GetTradeProductPack_ByTermResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Product Pack Code]", Storage="_Product_Pack_Code", DbType="VarChar(19) NOT NULL", CanBeNull=false)]
		public string Product_Pack_Code
		{
			get
			{
				return this._Product_Pack_Code;
			}
			set
			{
				if ((this._Product_Pack_Code != value))
				{
					this._Product_Pack_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Preferred Term]", Storage="_Preferred_Term", DbType="NVarChar(1000)")]
		public string Preferred_Term
		{
			get
			{
				return this._Preferred_Term;
			}
			set
			{
				if ((this._Preferred_Term != value))
				{
					this._Preferred_Term = value;
				}
			}
		}
	}
	
	public partial class GetTradeProductUnitOfUse_ByTermResult
	{
		
		private string _Unit_of_Use_Code;
		
		private string _Preferred_Term;
		
		public GetTradeProductUnitOfUse_ByTermResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Unit of Use Code]", Storage="_Unit_of_Use_Code", DbType="VarChar(19) NOT NULL", CanBeNull=false)]
		public string Unit_of_Use_Code
		{
			get
			{
				return this._Unit_of_Use_Code;
			}
			set
			{
				if ((this._Unit_of_Use_Code != value))
				{
					this._Unit_of_Use_Code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Preferred Term]", Storage="_Preferred_Term", DbType="NVarChar(1000)")]
		public string Preferred_Term
		{
			get
			{
				return this._Preferred_Term;
			}
			set
			{
				if ((this._Preferred_Term != value))
				{
					this._Preferred_Term = value;
				}
			}
		}
	}
	
	public partial class GetCttp_Related_IDs_ByCodeResult
	{
		
		private string _cttp_id;
		
		private string _cttp_pt;
		
		private string _tpp_id;
		
		private string _tpp_pt;
		
		private string _tpuu_id;
		
		private string _tpuu_pt;
		
		private string _tp_id;
		
		private string _tp_pt;
		
		private string _mpp_id;
		
		private string _mpp_pt;
		
		private string _mpuu_id;
		
		private string _mpuu_pt;
		
		private string _mp_id;
		
		private string _mp_pt;
		
		public GetCttp_Related_IDs_ByCodeResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cttp_id", DbType="VarChar(19) NOT NULL", CanBeNull=false)]
		public string cttp_id
		{
			get
			{
				return this._cttp_id;
			}
			set
			{
				if ((this._cttp_id != value))
				{
					this._cttp_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cttp_pt", DbType="NVarChar(1000)")]
		public string cttp_pt
		{
			get
			{
				return this._cttp_pt;
			}
			set
			{
				if ((this._cttp_pt != value))
				{
					this._cttp_pt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tpp_id", DbType="VarChar(19)")]
		public string tpp_id
		{
			get
			{
				return this._tpp_id;
			}
			set
			{
				if ((this._tpp_id != value))
				{
					this._tpp_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tpp_pt", DbType="NVarChar(1000)")]
		public string tpp_pt
		{
			get
			{
				return this._tpp_pt;
			}
			set
			{
				if ((this._tpp_pt != value))
				{
					this._tpp_pt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tpuu_id", DbType="VarChar(19)")]
		public string tpuu_id
		{
			get
			{
				return this._tpuu_id;
			}
			set
			{
				if ((this._tpuu_id != value))
				{
					this._tpuu_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tpuu_pt", DbType="NVarChar(1000)")]
		public string tpuu_pt
		{
			get
			{
				return this._tpuu_pt;
			}
			set
			{
				if ((this._tpuu_pt != value))
				{
					this._tpuu_pt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tp_id", DbType="VarChar(19)")]
		public string tp_id
		{
			get
			{
				return this._tp_id;
			}
			set
			{
				if ((this._tp_id != value))
				{
					this._tp_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tp_pt", DbType="NVarChar(1000)")]
		public string tp_pt
		{
			get
			{
				return this._tp_pt;
			}
			set
			{
				if ((this._tp_pt != value))
				{
					this._tp_pt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mpp_id", DbType="VarChar(19)")]
		public string mpp_id
		{
			get
			{
				return this._mpp_id;
			}
			set
			{
				if ((this._mpp_id != value))
				{
					this._mpp_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mpp_pt", DbType="NVarChar(1000)")]
		public string mpp_pt
		{
			get
			{
				return this._mpp_pt;
			}
			set
			{
				if ((this._mpp_pt != value))
				{
					this._mpp_pt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mpuu_id", DbType="VarChar(19)")]
		public string mpuu_id
		{
			get
			{
				return this._mpuu_id;
			}
			set
			{
				if ((this._mpuu_id != value))
				{
					this._mpuu_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mpuu_pt", DbType="NVarChar(1000)")]
		public string mpuu_pt
		{
			get
			{
				return this._mpuu_pt;
			}
			set
			{
				if ((this._mpuu_pt != value))
				{
					this._mpuu_pt = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mp_id", DbType="VarChar(19)")]
		public string mp_id
		{
			get
			{
				return this._mp_id;
			}
			set
			{
				if ((this._mp_id != value))
				{
					this._mp_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mp_pt", DbType="NVarChar(1000)")]
		public string mp_pt
		{
			get
			{
				return this._mp_pt;
			}
			set
			{
				if ((this._mp_pt != value))
				{
					this._mp_pt = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
