#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vintage.AppServices.DataAccessClasses
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PatientsFirst")]
	public partial class PatientsFirstDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public PatientsFirstDataContext() : 
				base(global::Vintage.AppServices.Properties.Settings.Default.PatientsFirstConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public PatientsFirstDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PatientsFirstDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PatientsFirstDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PatientsFirstDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ValidationResult_Insert")]
		public int ValidationResult_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApplicationName", DbType="NVarChar(100)")] string applicationName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApplicationVersion", DbType="NVarChar(10)")] string applicationVersion, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Specification", DbType="NVarChar(100)")] string specification, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PassedTransport", DbType="Bit")] System.Nullable<bool> passedTransport, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PassedFormat", DbType="Bit")] System.Nullable<bool> passedFormat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PassedData", DbType="Bit")] System.Nullable<bool> passedData, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReportTransport", DbType="NVarChar(1000)")] string reportTransport, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReportFormat", DbType="NVarChar(1000)")] string reportFormat, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReportData", DbType="NVarChar(1000)")] string reportData, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CreatedBy", DbType="NVarChar(50)")] string createdBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), applicationName, applicationVersion, specification, passedTransport, passedFormat, passedData, reportTransport, reportFormat, reportData, createdBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetHpiListing", IsComposable=true)]
		public IQueryable<GetHpiListingResult> GetHpiListing()
		{
			return this.CreateMethodCallQuery<GetHpiListingResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HpiOnLine_UpdateStatus")]
		public int HpiOnLine_UpdateStatus([global::System.Data.Linq.Mapping.ParameterAttribute(Name="HpiFacilityId", DbType="NVarChar(255)")] string hpiFacilityId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HpiOnLineStatus", DbType="Bit")] System.Nullable<bool> hpiOnLineStatus)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hpiFacilityId, hpiOnLineStatus);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetPractices_ByNamePho", IsComposable=true)]
		public IQueryable<GetPractices_ByNamePhoResult> GetPractices_ByNamePho([global::System.Data.Linq.Mapping.ParameterAttribute(Name="PracticeName", DbType="NVarChar(255)")] string practiceName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PracticeAddress", DbType="NVarChar(255)")] string practiceAddress, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PhoName", DbType="NVarChar(255)")] string phoName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DhbName", DbType="NVarChar(255)")] string dhbName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="VendorName", DbType="NVarChar(50)")] string vendorName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EDI", DbType="NChar(10)")] string eDI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Active", DbType="Bit")] System.Nullable<bool> active)
		{
			return this.CreateMethodCallQuery<GetPractices_ByNamePhoResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), practiceName, practiceAddress, phoName, dhbName, vendorName, eDI, active);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Gp2GpTransfers_Insert")]
		public int Gp2GpTransfers_Insert([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SenderEDI", DbType="NChar(10)")] string senderEDI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReceiverEDI", DbType="NChar(10)")] string receiverEDI, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MessageId", DbType="NVarChar(50)")] string messageId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MessageYear", DbType="SmallInt")] System.Nullable<short> messageYear, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MessageMonth", DbType="TinyInt")] System.Nullable<byte> messageMonth, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MessageDay", DbType="TinyInt")] System.Nullable<byte> messageDay, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ApplicationType", DbType="NVarChar(20)")] string applicationType, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FileSize", DbType="BigInt")] System.Nullable<long> fileSize, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SendingApplication", DbType="NVarChar(100)")] string sendingApplication, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ResponseMessageIndicator", DbType="Char(1)")] System.Nullable<char> responseMessageIndicator, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ReplyToMessageId", DbType="NVarChar(50)")] string replyToMessageId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MessageFileName", DbType="NVarChar(250)")] string messageFileName)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), senderEDI, receiverEDI, messageId, messageYear, messageMonth, messageDay, applicationType, fileSize, sendingApplication, responseMessageIndicator, replyToMessageId, messageFileName);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.Gp2GpTransfers_UpdateCollected")]
		public int Gp2GpTransfers_UpdateCollected([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gp2GpTransferId", DbType="Int")] System.Nullable<int> gp2GpTransferId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gp2GpTransferId);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetUncollectedGp2GpTransfers", IsComposable=true)]
		public IQueryable<GetUncollectedGp2GpTransfersResult> GetUncollectedGp2GpTransfers([global::System.Data.Linq.Mapping.ParameterAttribute(Name="HpiFacilityId", DbType="NVarChar(255)")] string hpiFacilityId)
		{
			return this.CreateMethodCallQuery<GetUncollectedGp2GpTransfersResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hpiFacilityId);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetGp2GpMessageFileName", IsComposable=true)]
		public string GetGp2GpMessageFileName([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Gp2GpTransferId", DbType="Int")] System.Nullable<int> gp2GpTransferId)
		{
			return ((string)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), gp2GpTransferId).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HimUserAuthenticate", IsComposable=true)]
		public System.Nullable<bool> HimUserAuthenticate([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string userID, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(50)")] string password)
		{
			return ((System.Nullable<bool>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userID, password).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.HpiOnLine_UpdateVersion")]
		public int HpiOnLine_UpdateVersion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="HpiFacilityId", DbType="NVarChar(255)")] string hpiFacilityId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="HimVersion", DbType="NVarChar(20)")] string himVersion)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), hpiFacilityId, himVersion);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class GetHpiListingResult
	{
		
		private string _HPI;
		
		private string _EDI;
		
		private System.Nullable<bool> _HPI_OnLine;
		
		public GetHpiListingResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HPI", DbType="NVarChar(255)")]
		public string HPI
		{
			get
			{
				return this._HPI;
			}
			set
			{
				if ((this._HPI != value))
				{
					this._HPI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDI", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string EDI
		{
			get
			{
				return this._EDI;
			}
			set
			{
				if ((this._EDI != value))
				{
					this._EDI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HPI_OnLine", DbType="Bit")]
		public System.Nullable<bool> HPI_OnLine
		{
			get
			{
				return this._HPI_OnLine;
			}
			set
			{
				if ((this._HPI_OnLine != value))
				{
					this._HPI_OnLine = value;
				}
			}
		}
	}
	
	public partial class GetPractices_ByNamePhoResult
	{
		
		private string _PracticeName;
		
		private string _PracticeId;
		
		private string _PracticeAddress;
		
		private string _PhoName;
		
		private string _DHB;
		
		private string _Region;
		
		private string _EDI;
		
		private string _PmsVendor;
		
		private bool _Gp2GpAdopter;
		
		private string _Closed;
		
		private int _Pkey;
		
		private bool _Rural;
		
		public GetPractices_ByNamePhoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PracticeName", DbType="NVarChar(255)")]
		public string PracticeName
		{
			get
			{
				return this._PracticeName;
			}
			set
			{
				if ((this._PracticeName != value))
				{
					this._PracticeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PracticeId", DbType="NVarChar(255)")]
		public string PracticeId
		{
			get
			{
				return this._PracticeId;
			}
			set
			{
				if ((this._PracticeId != value))
				{
					this._PracticeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PracticeAddress", DbType="NVarChar(255)")]
		public string PracticeAddress
		{
			get
			{
				return this._PracticeAddress;
			}
			set
			{
				if ((this._PracticeAddress != value))
				{
					this._PracticeAddress = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PhoName", DbType="NVarChar(255)")]
		public string PhoName
		{
			get
			{
				return this._PhoName;
			}
			set
			{
				if ((this._PhoName != value))
				{
					this._PhoName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DHB", DbType="NVarChar(255)")]
		public string DHB
		{
			get
			{
				return this._DHB;
			}
			set
			{
				if ((this._DHB != value))
				{
					this._DHB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Region", DbType="NVarChar(20)")]
		public string Region
		{
			get
			{
				return this._Region;
			}
			set
			{
				if ((this._Region != value))
				{
					this._Region = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EDI", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string EDI
		{
			get
			{
				return this._EDI;
			}
			set
			{
				if ((this._EDI != value))
				{
					this._EDI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PmsVendor", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string PmsVendor
		{
			get
			{
				return this._PmsVendor;
			}
			set
			{
				if ((this._PmsVendor != value))
				{
					this._PmsVendor = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gp2GpAdopter", DbType="Bit NOT NULL")]
		public bool Gp2GpAdopter
		{
			get
			{
				return this._Gp2GpAdopter;
			}
			set
			{
				if ((this._Gp2GpAdopter != value))
				{
					this._Gp2GpAdopter = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Closed", DbType="NVarChar(20)")]
		public string Closed
		{
			get
			{
				return this._Closed;
			}
			set
			{
				if ((this._Closed != value))
				{
					this._Closed = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pkey", DbType="Int NOT NULL")]
		public int Pkey
		{
			get
			{
				return this._Pkey;
			}
			set
			{
				if ((this._Pkey != value))
				{
					this._Pkey = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rural", DbType="Bit NOT NULL")]
		public bool Rural
		{
			get
			{
				return this._Rural;
			}
			set
			{
				if ((this._Rural != value))
				{
					this._Rural = value;
				}
			}
		}
	}
	
	public partial class GetUncollectedGp2GpTransfersResult
	{
		
		private int _Gp2GpTransferId;
		
		private string _MessageId;
		
		private string _MessageFileName;
		
		public GetUncollectedGp2GpTransfersResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gp2GpTransferId", DbType="Int NOT NULL")]
		public int Gp2GpTransferId
		{
			get
			{
				return this._Gp2GpTransferId;
			}
			set
			{
				if ((this._Gp2GpTransferId != value))
				{
					this._Gp2GpTransferId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageId", DbType="NVarChar(50)")]
		public string MessageId
		{
			get
			{
				return this._MessageId;
			}
			set
			{
				if ((this._MessageId != value))
				{
					this._MessageId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MessageFileName", DbType="NVarChar(250)")]
		public string MessageFileName
		{
			get
			{
				return this._MessageFileName;
			}
			set
			{
				if ((this._MessageFileName != value))
				{
					this._MessageFileName = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
